        <div>
            <h2>Input Expression:</h2>
            <input size="80" maxlength="80" id="input"/>
        </div>

            <br /><br />
        <div>
            <h2>Formatted Expression:</h2>
            <span id="formattedExpression"></span>

            <h2>Result:</h2>
            <span id="result"></span>
        </div>

            <br /><br /><hr />
        <div>
            <h3>Python Eval Expression:</h3>
            <span id="evalExpression"></span>
            
            <br />
            <h3>Python Eval Error:</h3>
            <span id="evalException">None</span>
        </div>
