#pragma once

template <class T>
class CProxy_IDlrComServerEvents : public IConnectionPointImpl<T, &__uuidof( _IDlrComServerEvents ), CComDynamicUnkArray>
{
	//Warning this class will  be regenerated by the wizard.
public:
};
