require 'rake'
require 'rake/testtask'
require 'rbconfig'
include Config

desc 'Install the facade package (non-gem)'
task :install do
   sitelibdir = CONFIG["sitelibdir"]
   file = "lib/facade.rb"
   FileUtils.cp(file, sitelibdir, :verbose => true)
end

task :install_gem do
   ruby 'facade.gemspec'
   file = Dir["*.gem"].first
   sh "gem install #{file}"
end

Rake::TestTask.new do |t|
   t.libs << 'test'
   t.verbose = true
   t.warning = true
   t.test_files = FileList['test/tc_facade.rb']
end