source 'http://rubygems.org'

gem 'rails', '3.0.1'
gem 'activerecord-sqlserver-adapter', :require => 'activerecord-sqlserver-adapter'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
