# ****************************************************************************
#
# Copyright (c) Microsoft Corporation. 
#
# This source code is subject to terms and conditions of the Microsoft Public License. A 
# copy of the license can be found in the License.html file at the root of this distribution. If 
# you cannot locate the  Microsoft Public License, please send an email to 
# ironruby@microsoft.com. By using this source code in any fashion, you are agreeing to be bound 
# by the terms of the Microsoft Public License.
#
# You must not remove this notice, or any other, from this software.
#
#
# ****************************************************************************
#

require 'rake'
require 'rake/tasklib'
$rakefile_path = File.dirname(__FILE__)
require $rakefile_path + '/context'

require 'tmpdir'
include REXML
include IronRubyUtils

verbose(false) # default to non-verbose output

IRONRUBY_COMPILER     = 'ir.exe'
CS_COMPILER           = mono? ? 'gmcs' : 'csc'
EXCLUDED_DIRECTORIES  = ['obj', '.', '..']


import File.dirname(__FILE__) + '/rake/test.rake'
import File.dirname(__FILE__) + '/rake/compile.rake'
import File.dirname(__FILE__) + '/rake/package.rake'
import File.dirname(__FILE__) + '/rake/misc.rake'
import File.dirname(__FILE__) + '/rake/git.rake'
