# -*- ruby -*-

require 'rake/clean'
require 'wix_rake'


CLEAN.include("Feature_*.wxs","*.wixobj","*.wixpdb", "*.log")
CLOBBER.include("*.msi")
ROOT_DIR = ENV['ROOT_DIR'] || "C:\\ironruby"
WIX_BIN = ENV['WIX_BIN'] || "#{ENV['MERLIN_ROOT']}\\External\\Wix3"
WIXOBJ = FileList["Core.wixobj", "IronRuby.wixobj", "Feature_Lib.wixobj", "Feature_Samples.wixobj", "Feature_Silverlight.wixobj"]

WixRake::Task.wix = WIX_BIN
WixRake::CandleTask.global_ext = ["WixNetFxExtension", "WixUtilExtension"]

heat(/Feature_(.+?)\.wxs/) do |r|
  r.root = ROOT_DIR
  r.opts = "-cg CG_#{r.target} -gg -nologo -dr APPLICATIONFOLDER -sw5151 -var var.IR#{r.target}"
  r.out = "Feature_#{r.target}.wxs"
end

candle("Core")

candle("IronRuby")

candle("Feature_Lib") do |c|
  c.vars = {"IRLib" => "#{ROOT_DIR}\\Lib", "IRSamples" => "#{ROOT_DIR}\\Samples", "IRSilverlight" => "#{ROOT_DIR}\\Silverlight"}
end

candle("Feature_Samples") do |c|
  c.vars = {"IRLib" => "#{ROOT_DIR}\\Lib", "IRSamples" => "#{ROOT_DIR}\\Samples", "IRSilverlight" => "#{ROOT_DIR}\\Silverlight"}
end

candle("Feature_Silverlight") do |c|
  c.vars = {"IRLib" => "#{ROOT_DIR}\\Lib", "IRSamples" => "#{ROOT_DIR}\\Samples", "IRSilverlight" => "#{ROOT_DIR}\\Silverlight"}
end

light '.msi' => WIXOBJ do |l|
  l.files = WIXOBJ
  l.includes = ROOT_DIR
  l.ext = %w{WixUIExtension WixNetFxExtension WixUtilExtension}
  l.opts = "-ss -sw1076 -sice:ICE57 -ice:ICE105"
end
