# -*- ruby -*-

require 'rubygems'
require 'hoe'

Hoe.spec 'ironruby-sqlserver' do
  developer 'Jimmy Schementi', 'jschementi@gmail.com'
  self.url = 'http://github.com/jschementi/ironruby-sqlserver'
  extra_deps << ['ironruby-dbi', '>=0']
  extra_deps << ['activerecord', '>=0']
  extra_deps << ['activerecord-sqlserver-adapter', '>=0']
end

# vim: syntax=ruby
