require 'rake'
require 'rake/clean'
require 'rake/testtask'
require 'rbconfig'
include Config

desc 'Build the ruby.exe.manifest if it does not already exist'
task :build_manifest do
   version = CONFIG['host_os'].split('_')[1]
   
   if version && version.to_i >= 80
      unless File.exist?(File.join(CONFIG['bindir'], 'ruby.exe.manifest'))
         Dir.chdir(CONFIG['bindir']) do
            sh "mt -inputresource:ruby.exe;2 -out:ruby.exe.manifest"
         end
      end
   end
end

desc 'Install the win32-api library (non-gem)'
task :install => [:build] do
   Dir.chdir('ext'){
      sh 'nmake install'
   }
end

task :install_gem do
   ruby 'win32-api.gemspec'
   file = Dir["*.gem"].first
   sh "gem install #{file}"
end

desc 'Clean any build files for Win32::API'
task :clean do
   Dir.chdir('ext') do
      if File.exists?('api.so') || File.exists?('win32/api.so') ||
         File.exists?('api.obj')
      then
         sh 'nmake distclean'
         rm 'win32/api.so' if File.exists?('win32/api.so')
         rm 'api.so' if File.exists?('api.so') 
      end
   end

   # Cleanup any files generated by the build_binary_gem task
   rm_rf('lib') if File.exists?('lib')
end

desc "Build Win32::API (but don't install it)"
task :build => [:clean, :build_manifest] do
   Dir.chdir('ext') do
      ruby "extconf.rb"
      sh "nmake"
      mv "api.so", "win32" # For the test suite
   end
end

desc 'Build a standard gem'
task :build_gem => [:clean] do 
   eval(IO.read('win32-api.gemspec'))
end

desc 'Build a binary gem'
task :build_binary_gem => [:build] do
   mkdir_p 'lib/win32'
   mv 'ext/win32/api.so', 'lib/win32'

   task :build_binary_gem => [:clean]

   spec = Gem::Specification.new do |gem|
      gem.name       = 'win32-api'
      gem.version    = '1.4.5'
      gem.authors    = ['Daniel J. Berger', 'Park Heesob']
      gem.license    = 'Artistic 2.0'
      gem.email      = 'djberg96@gmail.com'
      gem.homepage   = 'http://www.rubyforge.org/projects/win32utils'
      gem.platform   = Gem::Platform::CURRENT
      gem.summary    = 'A superior replacement for Win32API'
      gem.has_rdoc   = true
      gem.test_files = Dir['test/test*']

      gem.files = [
         Dir['*'],
         Dir['test/*'],
         'ext/extconf.rb',
         'ext/win32/api.c',
         'lib/win32/api.so'
      ].flatten.reject{ |f| f.include?('CVS') }

      gem.rubyforge_project = 'win32utils'
      gem.required_ruby_version = '>= 1.8.2'

      gem.extra_rdoc_files = [
         'README',
         'CHANGES',
         'MANIFEST',
         'ext/win32/api.c'
      ]
      
      gem.description = <<-EOF
         The Win32::API library is meant as a replacement for the Win32API
         library that ships as part of the standard library. It contains several
         advantages over Win32API, including callback support, raw function
         pointers, an additional string type, and more.
      EOF
   end

   Gem::Builder.new(spec).build
end

Rake::TestTask.new(:test) do |test|
   task :test => [:build]
   test.libs << 'ext'
   test.warning = true
   test.verbose = true
end

task :test do
   Rake.application[:clean].execute
end
