require 'rake'
require 'rake/testtask'
require 'rbconfig'
include Config

desc 'Install the win32-file-stat package (non-gem)'
task :install do
   sitelibdir = CONFIG['sitelibdir']
   installdir = sitelibdir + '/win32/file'
   basedir = File.dirname(installdir)
   file = 'lib\win32\file\stat.rb'
   
   Dir.mkdir(basedir) unless File.exists?(basedir)
   Dir.mkdir(installdir) unless File.exists?(installdir)
   FileUtils.cp(file, installdir, :verbose => true)
end

desc 'Install the win32-file-stat package as a gem'
task :install_gem do
   ruby 'win32-file-stat.gemspec'
   file = Dir["win32-file-stat*.gem"].first
   sh "gem install #{file}"
end

Rake::TestTask.new do |t|
   t.verbose = true
   t.warning = true
end