#
# Utilities for C# source file generation.
#

def generate(generator)
  file = generator.sub('Generator.rb', 'Generated.cs')
  gen_begin = '// *** BEGIN GENERATED CODE ***'
  gen_end = '// *** END GENERATED CODE ***'

  content = File.open(file, "rb") { |f| break f.read }
  
  content.sub!(/([^\r\n]*)#{Regexp.escape(gen_begin)}.*#{Regexp.escape(gen_end)}/m) do
     "#$1#{gen_begin}\r\n" +
     "#$1// Generated by #{File.basename(generator)}\r\n\r\n" +
     indent(yield, $1) +
     "\r\n\r\n" +
     "#$1#{gen_end}" 
  end  
  
  begin
    File.open(file, "wb") { |f| f.write(content) }
  rescue
    retry if tf_edit(file) 
    raise
  end
end

def tf_edit(file)
  `tf.exe edit #{file}`
  $?.exitstatus == 0
end

def indent(text, indentation)
  indentation + text.split("\n").join("\r\n" + indentation)
end