#!/usr/bin/env ruby

=begin
f = File.open "c:\\temp\\trace#{(defined? IRONRUBY_VERSION) ? 'IR' : 'MRI'}.log", "w+"
set_trace_func proc { |op, file, line, id, binding, cls|
  if op == "call" && id != :method_added 
    f.puts [file, line, cls, id].inspect
  end
}
=end

require File.dirname(__FILE__) + '/../config/boot'
require 'commands/server'
